### ISSUE TITLE
Alarm clock support?

### ISSUE THREAD

**Issue by lorenzorobbi** [hobbyquaker/homekit2mqtt#102]
is it possible to implement the support for the alarm using the standard layout of the hours and minutes of the iPhone?
Sorry for my ignorance.

**Comment by hobbyquaker** [comment]
The Apple standard services and characteristics don't offer that. One could create custom characteristics, but that would not be useable via Home app or Siri, so makes no sense from my point of view, as of today I only wanna support the services/characteristics that are "apple standard" (Perhaps I will do one exception and add some Elgato Eve characteristics in future).

**Comment by lorenzorobbi** [comment]
Thanks a lot for the answer!
