### ISSUE TITLE
Validate Commandline Arguments

### ISSUE THREAD

**Issue by abrownsword** [hobbyquaker/homekit2mqtt#105]
I have implemented a new accessory (actually it is my whole home automation system, thus it presents a couple dozen services), and am trying to use homekit2mqtt to bridge this to HAP/HomeKit.  The MQTT side of things seems to be working nicely -- my application generates the configuration json for the bridge, and launches homekit2mqtt with this command line (paths edited for brevity):

`Launching homekit bridge: homekit2mqtt --url=mqtt://192.168.0.102:1883 --verbosity=debug --mapfile=config/homekit.json --name=homekit-v0.2@hc1 --storagedir=config/homekit --port=51826 --web-port=51888 --username=homekit-v0.2@hc1 --pincode=666-00-999 --bridgename=homekit2mqtt &`

The bridge then prints a lot of debug messages, which all look as expected, including:

```
2018-07-02 11:12:01.208 <info>  loading HomeKit to MQTT mapping file config/homekit.json
2018-07-02 11:12:01.219 <debug> creating new accessory "mcp" "mcp" c3ecbf70-b781-4d07-b8df-5b51eb89dd5e
```
and after a bunch of adding/subscribing messages:
```
2018-07-02 11:12:01.304 <info>  hap created 1 Accessories
2018-07-02 11:12:01.347 <info>  hap publishing bridge "homekit2mqtt" username=homekit-v0.2@hc1 port=51826 pincode=666-00-999 setupURI=X-HM://0015210RRAJNH
2018-07-02 11:12:01.361 <debug> > mqtt homekit-v0.2@hc1/connected 2
2018-07-02 11:12:01.362 <info>  hap Bridge listening on port 51826

```
Followed by the QRcode image and the pincode box.  Then there are a series of <mqtt and >hap update messages.

Once it reaches a quiescent state (just a couple of seconds), I fire up the Home app on my iPad and attempt to add an accessory.  Neither the QR code nor pin find my accessory.  Have tried numerous times, various flavours and variations, changed instance name, user name, bridge name, etc.  Two different iOS11 devices.

Any suggestions as to why this isn't working?  I'm on the latest update version of homekit2mqtt, and a recent mosquitto server.

**Comment by s8mlu** [comment]
I may be running into a similar issue. Everything worked fine, but then for some unknown reasons, my HomeKit app would show "No Response" on the MQTT Bridge. If I don't touch anything except to remove the MQTT Bridge and add it again in the HomeKit app everything would work.

I looked at the homekit2mqtt log file and nothing unusual is happening. It is indeed connected to the MQTT server throughout this period. What do I need to do to debug this?

**Comment by hobbyquaker** [comment]
hmm... possibly a networking issue? In the past there was a user that had a Wifi Router that didn't forward broadcasts from LAN to Wifi.

**Comment by abrownsword** [comment]
Thanks for the suggestion.  I haven’t seen any such issues but broadcast from Ethernet to wifi isn’t very common.  I’m using an Apple AirPort access point — it isn’t the router.  I’ll have to figure out how to test that specifically.

**Comment by hobbyquaker** [comment]
Another thing that I would suggest: try it with a minimal config. Just add one Accessory with one Service.

**Comment by abrownsword** [comment]
Yes, I've been meaning to try with just one accessory.  Is there reason to suspect having multiple services as a problem?  Are there issues with having multiple (or many) services in one accessory?  I would rather not have to add many accessories, if I could avoid it.  But yes, will try with just 1 for testing purposes.

**Comment by hobbyquaker** [comment]
There is one downside with having multiple services in one accessory: Rooms are assigned to Accessories, not to Services, so all Services of a multi-service Accessory are forced to be in the same room. Besides that it is good practice to use multiple Services in one Accessory, so you don't reach the 100-Accessory-Limit to early ;-)

**Comment by abrownsword** [comment]
I refactored my code to create 1 accessory per room, and also did a quick check with only 1 service in 1 accessory.  Still nothing shows up in Home app on phone.

Still need to test for broadcasts from Ethernet to WiFi.

**Comment by abrownsword** [comment]
Sure enough, that was the problem.  It would be nice if it generated an error message if a required argument format wasn't met.   :)
