### ISSUE TITLE
[question] Extend a RGB light with effect selector

### ISSUE THREAD

**Issue by j4k3** [hobbyquaker/homekit2mqtt#108]
Hey,

so. I just successfully implemented a mqtt RGB light with WS2811 led strips for my living room with homekit2mqtt and am currently planing to light my whole home with similar DIY lights. Thanks for all contributors to this project!

Many of the smart home lighting solutions on the market, in addition to lights, have effects built in. Is there a way to extend the default RGB light controls with a selector and propagate its state via mqtt?

**Comment by hobbyquaker** [comment]
Only idea I have is to create some dummy switches that trigger your effects and add them to a HomeKit scene. The standard LightBulb Service doesn't offer Characteristics for that.

**Comment by j4k3** [comment]
Thanks for the reply!
