### ISSUE TITLE
camera cause other devices to unresponsive quickily!

### ISSUE THREAD

**Issue by kevinshane** [hobbyquaker/homekit2mqtt#116]
Hi, when stay in ios home app and waitting for the camera to refresh the snapshot, other devices suddently become all unresponosive(except for the camera itself still working), quit the ios home app and relaunch it doesn't fix this problem, unless drop the wifi and the reconnect to wifi again, other devices become normal, but still, a snapshot refresh again causing all others dead.
In log, everything seems normal, I only see this one
`ffmpeg -rtsp_transport tcp -i rtsp://192.168.0.120:8554/unicast -vframes 1 -r 1 -t 1 -s 480x270 -f image2 -`
`2018-08-11 18:31:12.442 <info>  Snapshot from CAM at 480x270`
In previous version everything is working btw.
Could u please take a look at this issue? Thanks!

**Comment by kevinshane** [comment]
updates:
Sorry about the rush, but it seems it happen randomly, or maybe it's my router's problem.
I will change my router to a new one and report here

**Comment by hobbyquaker** [comment]
I could only do guessing, don't have that issue here... If you want I can take a look at your config, also it would be interesting to get some info about the hardware homekit2mqtt is running on, is it a raspberry or smth or a more powerful server? ffmpeg can create quite a lot of load...

**Comment by kevinshane** [comment]
Hi sir @hobbyquaker after changing from a poor 6p to a iphonex, seems like it fix the problem at all, looks like there is a network(possible hardware issue) connection problem of that very old 6p, not sure if someone happen like this before... but now everything is working fine, sorry for the false alarm ^^..
I am using a more powerful sbc rather than a poor raspi, it's arm64v8 based with S905 chipset, 2gigs of ram, running armbian with docker hk2mqtt alpine.

**Comment by hobbyquaker** [comment]
Ok :) then I close this issue for now.
