### ISSUE TITLE
implement octoprint

### ISSUE THREAD

**Issue by m4gn3to** [hobbyquaker/homekit2mqtt#117]
It could be interesting: 

https://github.com/OctoPrint/OctoPrint-MQTT/blob/master/README.md

Thanks.

**Comment by hobbyquaker** [comment]
This is kinda out-of-scope for homekit2mqtt. Homekit2mqtt aims at being "end device agnostic", meaning that it can support everything that "speaks" mqtt, so you could already use homekit2mqtt to create services attached to your system via octoprint-mqtt. If you want "specialized" interfaces to specific end devices [homebridge](https://github.com/nfarina/homebridge) is most likely a better choice than homekit2mqtt.
