### ISSUE TITLE
Curtains randomly open.

### ISSUE THREAD

**Issue by MichMich** [hobbyquaker/homekit2mqtt#12]
I use your awesome script to control my self built electric curtains. It works perfect, but sometimes my curtains randomly open. I checked the debug info, and it doesn't say anything strange: it really looks like it really receives an open command from homekit:

````
 hap set Curtain 1 TargetPosition 100
````

The interesting thing is that when the last scene I used is a scene that opens 2 curtains. Only those two curtains open. If I recently controlled all 4 curtains. All 4 curtains open. It look like's Homekit toggles the most recent command. 

Any idea where to look for any clues or solutions?

**Comment by hobbyquaker** [comment]
hmm that s strange. i would suggest to
open an issue on the hap-nodejs repository and ask if someone else there has expirienced similar behavior with scenes and the windowcovering service. 
I only use homekit scenes to trigger dummy switches and further scene actions are done via node-red and/or mqtt-scripts in my setup. Until now I havent had issues with that.
Regards, 
Sebastian

**Comment by MichMich** [comment]
Opened an issue in het HAP-NodeJS repo.

**Comment by MichMich** [comment]
So, I probably found the issue. Which is 100% my fault: I was running the application on two different machines at the same time (by mistake). Homekit probably switches between the two different instances from time to time. I shut down one of the two instances, and will check if this solved the issue ... If not, I'll reopen the issue. Thanks!
