### ISSUE TITLE
camera "stillImageSource" can't not set to a web link

### ISSUE THREAD

**Issue by kevinshane** [hobbyquaker/homekit2mqtt#127]
Hi sir, I try to put the `stillImageSource` directly to the camera still image capture link, but it won't work, how to solve this? Thanks!
This can work:
`"stillImageSource": "-rtsp_transport tcp -i rtsp://192.168.0.120:8554/unicast -vframes 1 -r 1",`

This won't work:
`"stillImageSource": "http://192.168.0.120/cgi-bin/snapshot.cgi",`

**Comment by hobbyquaker** [comment]
try `"stillImageSource": "-i http://192.168.0.120/cgi-bin/snapshot.cgi"`

**Comment by kevinshane** [comment]
Thanks , it's now working!
