### ISSUE TITLE
Which arguments need to be stable for consistent accessory IDs?

### ISSUE THREAD

**Issue by abrownsword** [hobbyquaker/homekit2mqtt#131]
I am programmatically generating my configuration JSON file, as well as the arguments passed to homekit2mqtt.  My accessories appear in Home and I can add them, however if I restart my program and it regenerates the JSON and re-launches homekit2mqtt, then the accessories aren’t found by HomeKit.  I assume I am changing something (—name?) that needs to remain the same.  The documentation doesn’t say which values are used to create the HAP IDs (or whatever HomeKit uses).

**Comment by hobbyquaker** [comment]
The Key that defines your Accessory - see Readme:

```
"TemperatureSensor": {      // Unique name - used to generate the accessory UUID
  ...
}
```
