### ISSUE TITLE
What's different? same Service for one Accessory or split them all? 

### ISSUE THREAD

**Issue by kevinshane** [hobbyquaker/homekit2mqtt#137]
Hi Mr. @hobbyquaker, I have 3 lights which have the same service `lightbulb`, currently I split them to each accessory(id), in UI page I can see 3 ids for each light. I would like to know what's the exact differences when I "grouping" same "Service" to one Accessory(id)? I've already try with that and I found nothing, althrough it looks more cleaner in webUI. 😃 and I like that.

Also would you please help me how to setup the home app to "when a contact is open then pop up the camera preview"? (or we are not allowed to do that?) Does the `contact` and `camera` need to "group" them into one Accessory? Thanks

**Comment by hobbyquaker** [comment]
A Bridge is limited to 100 Accessories, if you exceed that limit you would need a second Bridge instance - that can be a good reason for grouping multiple Services in the same Accessory. 

The Downside is that all Services of one Accessory are always forced to be in the same room. If you move one Service in the Home App to another room all other Services of that Accessory are moved automatically too. 

Another thing is the BatteryService. If you want to be able to see Operating Voltage or Low Battery Warnings every battery supplied Device has to be a single Accessory.

See also https://github.com/hobbyquaker/homekit2mqtt/issues/56

**Comment by kevinshane** [comment]
Thanks, very clear explaination
