### ISSUE TITLE
Devices in "grey"

### ISSUE THREAD

**Issue by jsponz** [hobbyquaker/homekit2mqtt#145]
I have added a Temperature and Humidity sensors and I receive data, but the icons are in grey. 

<img width="793" alt="bildschirmfoto 2018-12-23 um 22 07 01" src="https://user-images.githubusercontent.com/12778286/50387563-96539d00-06ff-11e9-860d-e242cba8c3b7.png">

Is that normal?

**Comment by mattsheffiel** [comment]
That is normal for sensor accessories. The tiles only change for devices that turn on/off.

**Comment by jsponz** [comment]
Ok. Thanks for the confirmation.
