### ISSUE TITLE
Example payloads for LockMechanism incorrect (?)

### ISSUE THREAD

**Issue by Chordless** [hobbyquaker/homekit2mqtt#15]
I think i found an error in the example config (or i might have misunderstood something along the way). My lockmechanism worked correctly (opening and closing), but it would always report as being unsecured. Also, in the Home app on iOS, the lock status would just stay at "Locking..." indefinitely. 
 
I had to change the config from this:
```
"payload": {
      "lockUnsecured": "1",
      "lockSecured": "0"
 }
```
To this:
```
"payload": {
      "lockUnsecured": 1,
      "lockSecured": 0
 }
```
After that my lock reported status correctly.

P.S. Thanks for making this project, it's way cool.

**Comment by Chordless** [comment]
This issue can probably just be closed. I had not read through the mqtt-smarthome architecture document, and did not realize i was supposed to send a JSON-object with a "val" property containing my payload to the /status topic.

**Comment by hobbyquaker** [comment]
No, you're right. No matter if you're sending a mqtt-smarthome compliant `{"val":1}` or just the payload `1`it has to be of type number. I will fix the example asap, thanks for pointing on that.
