### ISSUE TITLE
Doorbell - which camera?

### ISSUE THREAD

**Issue by int2001** [hobbyquaker/homekit2mqtt#150]
I've got 3 Cams and one doorbell integrated in homekit2mqtt.

Is there any option to setup which camera "pops up" in Homekit, when the doorbell is pressed?
Can't find it. Or is the cam choosen by the HomeApp?

**Comment by hobbyquaker** [comment]
i think it just depends on the room. Try to assign the camera and the doorbell to the same room.

**Comment by int2001** [comment]
Yep, you're right. Thanks
