### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by Kevin-De-Koninck** [hobbyquaker/homekit2mqtt#153]
> Latest commit 8586e9a  on Aug 26, 2018

Is this project still maintained or is it abandoned?

**Comment by hobbyquaker** [comment]
I'm sorry that I didn't find time/motivation to work on this, but I'm still using it myself, so I won't call it "abandoned". I want to update the underlying HAP-Node.js and add the TV Accessories asap, give me some more time, can't promise when it will happen. I hope to get this done at the latest before christmas, maybe earlier.

**Comment by eXCepT74** [comment]
That will be big loss if you decide to leave this project. In my opinion its much better than HomeBridge which is too much complex and hard in use ( unless you know how to write plugins ).
Maybe people can organise some dotation for this project ?  
Best regards!
