### ISSUE TITLE
ContactSensor not changing state

### ISSUE THREAD

**Issue by tvillingett** [hobbyquaker/homekit2mqtt#2]
I cannot get this to work, is the contactsensor function tested?
I try to send mk/status/Ytterdorr/STATUS with { "var" : "door close" } and { "var" : "door open" } 

snippet from the homekit2mqtt.json
```json
    "mk//MK Ytterdörr": {
    "service" : "ContactSensor",
    "name" : "Ytterdörr",
    "topic": {
      "statusContactSensorState": "mk/status/Ytterdorr/STATUS"
    },
    "payload": {
        "onContactDetected" : "door closed"
    },
    "manufacturer": "Siemens",
    "model":        "MK 240"
  }
```

But it responses the same when I update the values on the iphone and get them sent to HAP:
(from log on screen)
```
< hap Ytterdörr get ContactSensorState
> hap Ytterdörr 1
```

**Comment by tvillingett** [comment]
I made a proposal for change...

**Comment by hobbyquaker** [comment]
Hi, I merged your PR and also improved the behavior of ContactSensor, it now notifies via setCharacteristic when the value changes.
Regards,
Sebastian
