### ISSUE TITLE
Cannot run the last version (0.6.2)

### ISSUE THREAD

**Issue by vasvlad** [hobbyquaker/homekit2mqtt#20]
See log:
/usr/bin/homekit2mqtt  -v
2016-11-19 21:55:23.808 <info>  homekit2mqtt 0.6.2 starting
2016-11-19 21:55:24.414 <info>  mqtt trying to connect mqtt://127.0.0.1
2016-11-19 21:55:24.469 <info>  using hap-nodejs version 0.4.15
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
2016-11-19 21:55:24.825 <info>  loading HomeKit to MQTT mapping file /usr/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json
/usr/lib/node_modules/homekit2mqtt/accessories/Thermostat.js:3
    var {mqttPub, mqttSub, mqttStatus, log, newAccessory, Service, Characteristic} = iface;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at loadAccessory (/usr/lib/node_modules/homekit2mqtt/index.js:168:28)
    at /usr/lib/node_modules/homekit2mqtt/index.js:179:9
    at Array.forEach (native)

**Comment by hobbyquaker** [comment]
pls take a look at the readme/prequisites, you need at least nodejs 5.1.0

**Comment by vasvlad** [comment]
I have installed the next version of nodejs:
nodejs -v
v5.12.0

**Comment by hobbyquaker** [comment]
and still the same error? shame on me, seems like I have documented wrong prerquisites... Could be that Node 5.x needs some harmony flag to enable object destructuring (that's the missing feature that leads to the error message). If you can I would suggest to update to the latest stable or lts node version (at the moment 6.9.1 or 7.1.0). Will correct the Readme asap.

**Comment by Maxmudjon** [comment]
npm ERR! Linux 4.4.32-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "homekit2mqtt"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! file /root/.npm/yalm/4.0.2/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: /root/.npm/yalm/4.0.2/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/npm-debug.log

**Comment by hobbyquaker** [comment]
Seems like the package.json file `/root/.npm/yalm/4.0.2/package/package.json`is corrupt. I would suggest to try:
```
sudo rm -r /root/.npm/yalm
sudo npm install -g homekit2mqtt
```

**Comment by hobbyquaker** [comment]
feel free to reopen if you want further assistance
