### ISSUE TITLE
GarageDoorOpener - Siri Issue

### ISSUE THREAD

**Issue by kentlefley** [hobbyquaker/homekit2mqtt#21]
I have the GarageDoorOpener working fine within the Home App, however Siri continually reports that the Garage Door is "opening" when asked the status.  I am using Mqtt to publish the status which shows correctly in the App, but somehow Siri is not aware.  

I'm a hardware guy and a bit of a software 'hack', but here is what I have for a configuration.  Any ideas?

Thanks

 "GarageDoorOpener": {
    "service":  "GarageDoorOpener",
    "name":     "North Garage Door",
    "topic": {
      "setDoor":          "GarageDoor/set",
      "statusDoor":       "GarageDoor/status"
    },
    "payload": {
      "doorOpen": 1,
      "doorClosed": 0
    },
    "manufacturer": "Generic",
    "model": "Generic"

**Comment by hobbyquaker** [comment]
Which version are you using? There was a bug thats probably related (see #19) that should be fixed with 0.6.3

**Comment by kentlefley** [comment]
I'll give that a try.  I am using version 0.6.2.
Can I just install the new version on top of the existing one?

**Comment by hobbyquaker** [comment]
Should be no problem. Only thing is: hap-nodejs saves some persistent data, homekit2mqtt has a commandline option for that (-s or --storagedir). If this is not set the hap-nodejs default is used, this is normally /usr/local/lib/node_modules/homekit2mqtt/node_modules/node-persist/persist or /usr/local/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/node_modules/node-persist/persist depending on which npm version you're using. 
Make a backup to be sure. I suggest using -s option and keep that persistent data outside of node_modules.

**Comment by kentlefley** [comment]
Updated to version 0.6.5 and took your advice on using the -s switch.  Siri now reports either door "opening" or "closing" instead of "open" or "closed".  Once again, the app reports correctly however Siri seems to think that the operation is not complete.

Thanks for the help so far,I appreciate it.

**Comment by hobbyquaker** [comment]
Will do some tests and check back to you asap.

**Comment by kentlefley** [comment]
Thank you for your help.  An update to IOS 10.2 on my phone seems to have corrected the issue.

Thanks

Kent

**Comment by hobbyquaker** [comment]
so this Issue can be closed?

**Comment by kentlefley** [comment]
I believe so.  Seems to be working fine

Thanks
