### ISSUE TITLE
a bug in Thermostate.js 

### ISSUE THREAD

**Issue by zenz** [hobbyquaker/homekit2mqtt#23]
from line 59, the var state was statically point to 1, this make the homekit always in heating mode.
it should be modified to this:

```
thermo.getService(Service.Thermostat)
            .getCharacteristic(Characteristic.CurrentHeatingCoolingState)
            .on('get', function (callback) {
                log.debug('< hap get', settings.name, 'CurrentHeatingCoolingState');
                // var state = 1; // hei! this make it always in heating mode。
                // log.debug('> hap re_get', settings.name, 'CurrentHeatingCoolingState', state);
                // callback(null, state);
                log.debug('> hap re_get', settings.name, 'CurrentHeatingCoolingState', mqttStatus[settings.topic.statusCurrentHeatingCoolingState]);
                callback(null, mqttStatus[settings.topic.statusCurrentHeatingCoolingState]);
            });
```

and then in the item configuration file, should add a topic to replay the currentmode
"statusCurrentHeatingCoolingState": "/sensor1/status/HeatingCoolingState"
something like that.

**Comment by hobbyquaker** [comment]
ack :) I set it to 1 because I only have heatings here, no coolings. I will implement that asap. Or you send me a PR :)

**Comment by davea** [comment]
I've opened PR #27 which fixes this, as well as a few other bits.

**Comment by hobbyquaker** [comment]
Thx to @davea you can now define a mqtt topic for the `statusCurrentHeatingCoolingState` characteristic (off=0, heat=1, cool=2).
