### ISSUE TITLE
Does HAP-NodeJS needed to already be installed?

### ISSUE THREAD

**Issue by jat80** [hobbyquaker/homekit2mqtt#25]
Does HAP-NodeJS needed to already be installed for this to work or does this install hap-nodejs as well?

I already have HAP-NodeJs on my raspberry pi - what would be the process to install this?

**Comment by hobbyquaker** [comment]
No, HAP-NodeJs should be installed as dependency of homekit2mqtt, no need to do that manually. If you have already installed it and you want't to re-use your settings you would have to take care of the files HAP-Nodejs is creating, in default they reside somewhere inside the "persist" module, for homekit2mqtt you can use the `--storagedir` option to change the path of these files.
