### ISSUE TITLE
"GarageDoor" status on startup

### ISSUE THREAD

**Issue by raufis27** [hobbyquaker/homekit2mqtt#29]
Sorry if I missed something in configuration. GarageDoor sensor reports OPEN when homekit2mqtt restarts. Is there any way to set default to CLOSE ? Same for example with Alarm, on restart it reports HOME, I'll prefer OFF. 

Thank you.

**Comment by hobbyquaker** [comment]
hmmm... are the corresponding messages published with `retain` flag set to true on mqtt?

**Comment by hobbyquaker** [comment]
Another possible cause of this could be a type mismatch on settings.payload.doorClosed - can you pls show your configuration for this accessory?

**Comment by raufis27** [comment]
Here is log - 2017-06-17 12:49:48.705 <debug> < hap get Garage Door CurrentDoorState
2017-06-17 12:49:48.705 <debug> > hap re_get Garage Door CurrentDoorState.OPEN

"GarageDoor": {
    "service": "GarageDoorOpener",
    "name": "Garage Door",
    "topic": {
      "setDoor": "/myhome/garage/command",
        "statusDoor": "/myhome/garage/state"
    },
    "payload": {
      "doorOpen": true,
        "doorClosed": false
    },
    "manufacturer": "RiHome",
    "model": "GarageDoor"
  },

BTW same with Lights, all Lights set to 0 on app restart. 

"LivingRoomLight": {
    "service":  "Lightbulb",
    "name":     "Living Room Lights",
    "topic": {
      "setOn":            "/myhome/in/command/zwave_device_1590aeb5569_node6_switch_dimmer",
      "setBrightness":    "/myhome/in/command/zwave_device_1590aeb5569_node6_switch_dimmer",
      "statusOn":         "/myhome/state/zwave_device_1590aeb5569_node6_switch_dimmer",
      "statusBrightness": "/myhome/state/zwave_device_1590aeb5569_node6_switch_dimmer",
      "identify":         "/myhome/in/command/zwave_device_1590aeb5569_node6_switch_dimmer"
    },

"payload": {
      "onTrue": 100,
      "onFalse": 0,
      "identify": "select"
    },
    "manufacturer": "iHome",
    "model": "Lightbulb Dimmable"
  },

**Comment by hobbyquaker** [comment]
could you please paste the output of `mosquitto_sub -t /myhome/garage/state -v`

**Comment by raufis27** [comment]
I am using mosquitto installed on synology, so unfortunately mosquitto_sub command not supported. I have mqttfx client on Mac, if it helps ?

**Comment by hobbyquaker** [comment]
yes sure. i'd just like to see the payload and if the message is retained. just post a screenshot

**Comment by raufis27** [comment]
Fixed. You are right, issue was in OH mqtt config, message retain was FALSE. Thanks for your help.
