### ISSUE TITLE
Not possible to set targettemperature above 35 degrees

### ISSUE THREAD

**Issue by tvillingett** [hobbyquaker/homekit2mqtt#3]
I'm not sure if this is in HAP-NodeJS or the app used for changing the value (EVE home) or some other change.
The water temperature has a setpoint of 60 at home, but I guess the temperature settings are meant only for Air temperature.
The value is not updated on screen if it is above 35, and the value can temporary bet set to a slightly higher value

**Comment by hobbyquaker** [comment]
AFAIK HomeKit specs limit TargetTemperature to 38°C

**Comment by hobbyquaker** [comment]
I learned now that this is a property that can be changed :)
davea made a pull request that gives access to these properties from the homekit2mqtt.json config file, see the "props" section under "Thermostat" in the Readme.
