### ISSUE TITLE
Thermostat targetTemperature prop case

### ISSUE THREAD

**Issue by sillyfrog** [hobbyquaker/homekit2mqtt#31]
I have noticed that the "targetTemperature" prop for a Thermostat does not work, after a quick look at the code and some playing around, it should be "TargetTemperature" (uppercase T at the start).

I'm not sure the best way to fix it (I think updating the code to allow for "targetTemperature", but wanted to leave that to you as I'm not familiar with the code).

If there is anything I can do, please let me know.

PS: Thanks for this project, it's great and starting to become the core of my (new) home automation - really appreciate it!

**Comment by hobbyquaker** [comment]
It should be uppercase, I fixed it in the Readme. Thanks for pointing this out and for your Feedback 👍
