### ISSUE TITLE
Outlet accessory error

### ISSUE THREAD

**Issue by nicolarampini** [hobbyquaker/homekit2mqtt#33]
Hello,
I noticed that when I added an Oulet accessory the terminal reported: 
Error: Cannot add a Service with the same UUID '00000047-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.

**Comment by hobbyquaker** [comment]
Thx for reporting this Bug, should be fixed in v0.6.11
