### ISSUE TITLE
Speaker "Not Supported" in iOS Home app

### ISSUE THREAD

**Issue by tardisx** [hobbyquaker/homekit2mqtt#36]
Thank you for fixing #35 !

Now the accessory is created (and no crash) but in Home on iOS, it merely shows "Not Supported" for the Speaker.

There's no related logs in homekit2mqtt output.

I'm running iOS 10.3.3. Is this an iOS 11 feature?

I've just implemented just the minimal configuration:

````
{
  "Speaker": {
    "service": "Speaker",
    "name": "Speaker",
    "topic": {
      "setMute": "home/speaker/mute"
    },
    "payload": {
      "muteTrue": "mute",
      "muteFalse": "unmute"
    }
  }
}
````

Is there anything useful I can do to debug this?

**Comment by hobbyquaker** [comment]
Yes, the iOS 10 Home app doesnt support speakers. You can use them with the Elgato Eve app.
