### ISSUE TITLE
Problem with setOn in LightBulb

### ISSUE THREAD

**Issue by sembsa** [hobbyquaker/homekit2mqtt#37]
Problem with LightBulb, this not remember 'setOn', when I set off, close HomeApp and open Light is on and should be off

```
2017-08-23 03:04:52.769 <debug> < hap set Test Philips On 0
2017-08-23 03:04:52.773 <debug> > mqtt /home/setOn false
2017-08-23 03:05:01.526 <debug> < hap get Test Philips On
2017-08-23 03:05:01.529 <debug> > hap re_get Test Philips On true
```

```
{
  "TestPhilips": {
    "id": "TestPhilips",
    "name": "Test Philips",
    "service": "Lightbulb",
    "topic": {
      "setOn": "/home/setOn",
      "setBrightness": "/home/setB",
      "setColorTemperature": "/home/setColor",
      "identify": "test1"
    },
    "payload": {
      "onTrue": true,
      "onFalse": false,
      "brightnessFactor": "",
      "hueFactor": "",
      "saturationFactor": ""
    },
    "config": {}
  }
}
```

**Comment by hobbyquaker** [comment]
You need to define a topic for `statusOn` on which the actual state of the lamp is reported. 
I guess you're using a Philips Hue Bridge? How did you connect it to MQTT? Perhaps it's worth to take a look at https://github.com/hobbyquaker/hue2mqtt.js

**Comment by sembsa** [comment]
thanks, for reply. I have Philips Xiaomi LED Bulb, and I want connect to homekit :)

**Comment by hobbyquaker** [comment]
Ah ok :) If you're MQTT interface to the lamp doesn't report the actual status you could also try to just set `statusOn` to the same topic as `setOn`.

**Comment by sembsa** [comment]
Thank you very much, I like your project very much. Grow it further! I managed to create something like this https://github.com/sembsa/PhilipsLEDBulb-homekit
