### ISSUE TITLE
iOS 11 Compatibility. Can't find bridge.

### ISSUE THREAD

**Issue by raufis27** [hobbyquaker/homekit2mqtt#39]
Any ideas when iOS 11 will be supported ?

Thank you

**Comment by hobbyquaker** [comment]
It should be fully compatible with iOS 11 - I have no problems using it with iOS 11. Perhaps it's worth a try to supply the `--username` option with a changed address, could be that your iOS device still knows another bridge under the same address.

**Comment by raufis27** [comment]
Can you try to setup new bridge? Update from iOS 10 to 11 works. But see what happens if you want to setup bridge from scratch in ios11.

**Comment by hobbyquaker** [comment]
Will try it this weekend

**Comment by hobbyquaker** [comment]
One question: you are aware of that only **one** iOS device can be paired with a Homekit Bridge?

**Comment by raufis27** [comment]
Yes. 

Here is similar issue - https://github.com/nfarina/homebridge/issues/1491

Honestly I didn't do full reset and test (because I don't want to loose my setup), but tried to find bridge on freshly installed iOS11 and it failed. Adding accessory procedure also looks different in ios11.

**Comment by hobbyquaker** [comment]
Ok, did a test. I just started another homekit2mqtt instance on my laptop (of course with different `--username` and `--bridgename`) and was able to pair it with iOS 11. 
Where exactly starts your Problem? Can't you see the bridge at all? Or can you see it and the pairing fails? Are you absolutely sure that no other iOS device is still paired with the bridge (did you explicitly delete the bridge from previously paired iOS devices or does the bridge possibly still "think" it is paired)?

**Comment by raufis27** [comment]
Thank you! I couldn’t see bridge at all. I’ll do reset this weekend and test it. 
You can close this issue, I’ll report back if I still have a problem.
