### ISSUE TITLE
Sprinkler and other new devices

### ISSUE THREAD

**Issue by sillyfrog** [hobbyquaker/homekit2mqtt#41]
Would it be possible to add in support for the new iOS 11 devices such a sprinkler and faucet? I'm currently using a switch for my sprinkler, and that would be good to use this new feature.

Thanks!

PS: I'm loving the new web interface!

**Comment by hobbyquaker** [comment]
If I understand that right the sprinkler isn't available until now. See https://github.com/KhaosT/HAP-NodeJS/issues/504
Let us keep this Issue open, as soon as the sprinkler is available in HomeKit and HAP-NodeJS I will add it.
And thanks for your Feedback! :)

**Comment by sillyfrog** [comment]
Thanks for getting back to me, looking forward to testing it when it's ready.

**Comment by hobbyquaker** [comment]
v0.7.8 implements faucet, irrigationSystem and valve.
