### ISSUE TITLE
Paring lost on restart

### ISSUE THREAD

**Issue by sillyfrog** [hobbyquaker/homekit2mqtt#42]
I have recently upgraded from v0.6.10 to v0.7.2. After upgrading I needed to reconnect my iPhone to homekit2mqtt, I thought this was just a one off but now I have restarted homekit2mqtt again, I've found my iPhone has lost connectivity. Looking at the debug logs does not show any hints as to the issue. I have run a tcpdump and included the relevant parts below, best I can tell is not trusting the phone any more.

```
POST /pair-verify HTTP/1.1
Host: MQTT\032Bridge._hap._tcp.local
Content-Length: 37
Content-Type: application/pairing+tlv8


HTTP/1.1 403 Forbidden
Date: Sun, 29 Oct 2017 02:34:15 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```

This is the command I'm using to run homekit2mqtt, the main change from the 0.6.10 is the addition of the `--storagedir` option:
```
/usr/bin/homekit2mqtt -v debug --url mqtt://mos.host --mapfile /homekit2mqtt/conf/homekit2mqtt.json --storagedir /homekit2mqtt/persist/
```

**Comment by sillyfrog** [comment]
Further to this, in writing the above I realised the only change was the `--storagedir` option. So am now running the following command, and things are working correctly after restart.
```
/usr/bin/homekit2mqtt -v debug --url mqtt://mos.host --mapfile /homekit2mqtt/conf/homekit2mqtt.json
```


So I guess the new `--storagedir` option is the issue.
Cheers.

**Comment by hobbyquaker** [comment]
Will try to look into this on the next weekend.

**Comment by hobbyquaker** [comment]
I tried to reproduce this, but I couldn't. Works for me, also with the `--storagedir` option. Could this possibly be caused by access rights to your directory `/homekit2mqtt/persist/`? Did this directory exist and did the user running homekit2mqtt have write access to it?

**Comment by hobbyquaker** [comment]
Closing this. Feel free to reopen if still an issue.

**Comment by sillyfrog** [comment]
Thanks for looking at this - sorry for not getting back to you sooner I have been away without internet. It has not happened to me either on the latest build - so I'm very confused, apologies for the run around.

Cheers!
