### ISSUE TITLE
Run in background mode?

### ISSUE THREAD

**Issue by arjan-io** [hobbyquaker/homekit2mqtt#43]
Hi,

First of all, thanks for this great code!

I've tried fire homekit2mqtt up via and putty shows:
```
 sudo homekit2mqtt
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
2017-11-08 16:03:20.374 <info>  homekit2mqtt 0.7.2 starting
2017-11-08 16:03:20.384 <info>  mqtt trying to connect mqtt://127.0.0.1
2017-11-08 16:03:20.595 <info>  using hap-nodejs version 0.4.36
2017-11-08 16:03:20.622 <info>  loading HomeKit to MQTT mapping file /usr/local/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json
2017-11-08 16:03:20.736 <info>  hap created 10 Accessories
2017-11-08 16:03:20.737 <info>  hap publishing bridge "MQTT Bridge" username=CC:22:3D:E3:CE:F6 port=51826 pincode=031-45-154
2017-11-08 16:03:20.852 <info>  hap Bridge listening on port 51826
2017-11-08 16:03:20.853 <info>  http server listening on port 51888
2017-11-08 16:03:20.882 <info>  mqtt connected mqtt://127.0.0.1
```
After the last line, there is an empy line but no cursor. In other words, this putty window is now useless but I guess I have to keep it open to keep homekit2mqtt running.

Is there any way of running the program in background mode? I tried the usual '&' sign on the end but to no avail. Sorry if the solution is obvious but I am kind of stuck.

Thank you in advance.

**Comment by raufis27** [comment]
What is you OS ? Linux or Mac ?

**Comment by barto-** [comment]
You can try `nohup`

**Comment by hobbyquaker** [comment]
I suggest either to use https://github.com/Unitech/pm2 or to create a systemd service (see e.g. http://nodesource.com/blog/running-your-node-js-app-with-systemd-part-1/)

**Comment by raufis27** [comment]
You can run homekit2mqtt on startup using cron. Do - 
crontab -e
@reboot homekit2mqtt [options]

Or 
use rc-local [(https://www.raspberrypi.org/documentation/linux/usage/rc-local.md)] to setup startup script.

**Comment by raufis27** [comment]
You can run homekit2mqtt on startup using cron. Do - 
crontab -e
@reboot homekit2mqtt [options]

Or 
use rc-local [(https://www.raspberrypi.org/documentation/linux/usage/rc-local.md)] to setup startup script.

**Comment by raufis27** [comment]
You can run homekit2mqtt on startup using cron. Do - 
crontab -e
@reboot homekit2mqtt [options]

Or 
use rc-local https://www.raspberrypi.org/documentation/linux/usage/rc-local.md to setup startup script.

**Comment by sembsa** [comment]
Hi i have service:

[Unit]
Description=Strt HomeKit2MQTT

[Service]
ExecStart=/usr/local/bin/homekit2mqtt -p 51829 -v debug
StandardOutput=journal

[Install]
WantedBy=multi-user.target
Alias=homekit2mqtt.service


You need to copy the /etc/systemd/system/homekit2mqtt.service file, paste the code and then type:
`sudo systemctl deamon-reload`
`sudo systemctl enable homekit2mqtt`
`sudo systemctl start homekit2mqtt`

**Comment by sembsa** [comment]
Hi i have service:

[Unit]
Description=Strt HomeKit2MQTT

[Service]
ExecStart=/usr/local/bin/homekit2mqtt -p 51829 -v debug
StandardOutput=journal

[Install]
WantedBy=multi-user.target
Alias=homekit2mqtt.service


You need to copy the /etc/systemd/system/homekit2mqtt.service file, paste the code and then type:
`sudo systemctl deamon-reload`
`sudo systemctl enable homekit2mqtt`
`sudo systemctl start homekit2mqtt`

**Comment by sembsa** [comment]
Hi i have service:

[Unit]
Description=Strt HomeKit2MQTT

[Service]
ExecStart=/usr/local/bin/homekit2mqtt -p 51829 -v debug
StandardOutput=journal

[Install]
WantedBy=multi-user.target
Alias=homekit2mqtt.service


You need to copy the /etc/systemd/system/homekit2mqtt.service file, paste the code and then type:
`sudo systemctl deamon-reload`
`sudo systemctl enable homekit2mqtt`
`sudo systemctl start homekit2mqtt`

**Comment by arjan-io** [comment]
Oke, few options here. Thanks for the responses. I'll close the Issue for now and will reopen if I get stuck. Cheers.
