### ISSUE TITLE
Updating devices when locked takes a long time

### ISSUE THREAD

**Issue by CosminLazar** [hobbyquaker/homekit2mqtt#49]
When viewing my devices in the action center by swiping from the bottom up it sometimes takes a long time for the devices to update their status, they just sit there "updating". This is sometimes fixed by closing the action center, unlocking the phone and opening the action center again.

Is this something that you also experience or is it just me?

Last but not least, thank you for the great work you have put in this project!

**Comment by hobbyquaker** [comment]
Hmm... For me it's working quite fast, I guess < 1s. Can you provide homekit2mqtt debug output from the moment you start Home view in action center until update is done?

**Comment by CosminLazar** [comment]
Thank you, will get back with a log after the holidays.

**Comment by CosminLazar** [comment]
The issue seems to have stopped. Let's close this, I know what to do if it happens again. Thank you for the support!
