### ISSUE TITLE
connecting to existing mqtt server [assistance required]

### ISSUE THREAD

**Issue by donster22** [hobbyquaker/homekit2mqtt#52]
hi. probably super simple but please can i ask where / how i configure my current mqtt server, port, username and password? i've read, reread and looked through all the files but can't find anything that looks configurable for me. cheers, don

**Comment by hobbyquaker** [comment]
You have to supply a MQTT url with the option `-u`.
Example:
You have a MQTT server listening on 192.168.1.20, Port 1883, User: abc, Pass: xyz
`-u mqtt://abc:xyz@192.168.1.20:1883`

If you want to connect with TLS use `mqtts://`.

**Comment by donster22** [comment]
perfect, thank you. that works a treat. what's the best way to start it on boot? I've tried crontab but that's not working. cheers, don
