### ISSUE TITLE
Accessories with multiple services

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/homekit2mqtt#56]
makes sense? needed?

**Comment by mattsheffiel** [comment]
I experimented creating accessories with multiple services and found that the Home app handles them differently depending on the individual circumstances.

![accessories](https://user-images.githubusercontent.com/29007028/34643724-b16fe632-f2ee-11e7-817c-08323310f969.png)

In this screenshot I've drawn borders around what are single accessories with multiple services. As you can see the Home app in the case of sensors and outlets will display them individually which makes sense to me.

If you add the battery service to an accessory the Home app is intelligent enough to show this information under details and not create an additional tile. In the case of a sensor with multiple services such as temp, humidity, etc. it will mirror the battery percentage and charging information under the details for each tile in the app. It should also be noted that the low battery characteristic from the battery service supersedes the built in low battery characteristics for other services. In other words the built in low battery characteristic is ignored by the Home app when the battery service is used on the same accessory.

![img_0469](https://user-images.githubusercontent.com/29007028/34643708-8224910c-f2ee-11e7-8683-bc2fcb5ff401.png)

Stateless programmable switches are another instance in which it makes sense the have multiple services under a single accessory. This is the service type used to expose the Philips Hue dimmer switches which have four separate buttons. Without grouping multiple services under one accessory there would be a tile for each button in the Home app while grouping them under one accessory will display them under the details of one tile which is considerably less cluttered.

![img_0470](https://user-images.githubusercontent.com/29007028/34643716-a048f240-f2ee-11e7-861f-ce7866e68c5b.png)

It seems that Apple intends for accessories with multiple services to be implemented this way. I think it may be beneficial to look into what changes would be necessary to make this possible going forward as new accessories and services will probably continue to follow this pattern.

I should probably also note that I did these tests using the HomeKit Accessory Simulator and not HAP-NodeJS so I don't yet know if it supports accessories with multiple services.

**Comment by hobbyquaker** [comment]
Great, thanks for the research! HAP-NodeJS supports this (afaik, quite sure). Will need some time to figure out how homekit2mqtt configuration can be adapted to a multi-service accessory model. If you have ideas or suggestions they are highly appreciated! :)

**Comment by hobbyquaker** [comment]
A first thought about config schema: just put the services like they are now in an array if there are more than 1 in a accessory. E.g.:
```json
  "TemperatureSensor": [{                         
    "service": "TemperatureSensor",                       
    "name": "TemperatureSensor",                         
    "topic": {                                              
        // ... MQTT Topic Configuration ...
    },
    "payload": {
        // ... MQTT Payload Configuration ...
    }
}, {
 "TemperatureSensor": [{                         
    "service": "BatteryService",                       
    "topic": {                                              
        // ... MQTT Topic Configuration ...
    },
    "payload": {
        // ... MQTT Payload Configuration ...
    }
}]
```

One premise: if possible it should be kept compatible, so that homekit2mqtt can still continue to work with existing configs. Would be easy with the above schema, jetzt check if there's an array or not. Changing the config scheme and the accessory creation is not that big deal, can be done on one evening. But adopting the Config-Web-Interface will be a lot more work, can't promise when I will find time to that....

**Comment by mattsheffiel** [comment]
> A question that should be clarified is how to handle the name attribute, right now I don't now if thats an accessory or an service property, have too check.

It seems to be both. If an accessory has a temperature and humidity service the name characteristic for each service shows as the name on the respective tile in the Home app. The name characteristic for the accessory is ignored in this case.

In the case of an accessory with multiple stateless programmable switches the name characteristic for the accessory is show on the tile and the name assigned to the individual services (individual buttons) are not displayed. The are just named "Button 1," "Button 2," etc. 

The Elgato Eve app shows both the name characteristics associated with the accessory and the individual services, however.

> But adopting the Config-Web-Interface will be a lot more work, can't promise when I will find time to that, but I will give that high priority on my Github Todo ;-)

I understand. That isn't a problem. I'm willing to help in any way I possibly can. I'm just not that familiar with NodeJS so I may cause more problems than solutions. 

Regarding the config file I think this would break compatibility but it may be unavoidable. Would something like this work?
```
{
   "SensorAccessory": {
      "name": "Sensor",
      "manufacturer": "some company",
      "model": "some model",
      "services": 
      [{
         "service": "TemperatureSensor",
         "name": "Temperature Sensor",
         "topic": {

         },
         "payload": {

         }
      },
      {
         "service": "HumidityService",
         "name": "Humidity Sensor",
         "topic": {

         },
         "payload": {

         }
      }]
   }
}
```

**Comment by hobbyquaker** [comment]
Yes, your scheme looks better. I think we can keep it backwards compatible, the Accessory creation function has just to check if there is a `services` array and if not fall back to the old behavior with a `service` property.
About your Node.js skills: just do it, if you have time & motivation :) if I think there is something that has to be changed on a PR I will try to guide you ;-)

**Comment by hobbyquaker** [comment]
@mattsheffiel So, backend implementation is nearly done, it's following your schema suggestion, you should now be able to use multiple services on one accessory. :-)
But this was only the easy part - it's not yet possible to configure multi-service-accessories in the web ui, this will be a bit more work. But you can already test it if you edit the mapping json manually. Until now it's not published on npm, so you need to git clone this repo.

**Comment by hobbyquaker** [comment]
Btw.: the old config scheme is still compatible, if you have a definition of `service`, `topic`, `payload` etc outside the `services` array it is added as the first service of the accessory.

**Comment by mattsheffiel** [comment]
Awesome! Thanks so much for doing this.

I'll try and test it out later today. I don't mind having to edit the config file manually.

**Comment by mattsheffiel** [comment]
If I copy the `/perist` folder and files I should be able to maintain my previous pairing even if I'm running this code in another directory, right?

**Comment by hobbyquaker** [comment]
yes. But I would advise to use the `--storagedir` option to keep the persistence data outside of the homekit2mqtt directory.

**Comment by mattsheffiel** [comment]
I've got to do some more testing but it all seems to be working as expected. Great job!

I did get an error when I initially paired with my test machine that I don't remember seeing before so I'll post it below. It may just be something I didn't do correctly. I haven't had a chance to look into it in detail.

```
2018-02-15 20:43:52.934 <info>  < hap bridge identify (paired)
/Users/matthewsheffield/Code/homekit2mqtt/index.js:147
    if (settings.topic.identify) {
                       ^

TypeError: Cannot read property 'identify' of undefined
    at identify (/Users/matthewsheffield/Code/homekit2mqtt/index.js:147:24)
    at Accessory.acc.on (/Users/matthewsheffield/Code/homekit2mqtt/index.js:172:9)
    at emitTwo (events.js:126:13)
    at Accessory.emit (events.js:214:7)
    at Accessory._identificationRequest (/Users/matthewsheffield/Code/homekit2mqtt/node_modules/hap-nodejs/lib/Accessory.js:122:10)
    at Accessory.<anonymous> (/Users/matthewsheffield/Code/homekit2mqtt/node_modules/hap-nodejs/lib/Accessory.js:80:14)
    at emitMany (events.js:147:13)
    at Characteristic.Identify.emit (events.js:224:7)
    at Characteristic.Identify.Characteristic.setValue (/Users/matthewsheffield/Code/homekit2mqtt/node_modules/hap-nodejs/lib/Characteristic.js:292:10)
    at Bridge.<anonymous> (/Users/matthewsheffield/Code/homekit2mqtt/node_modules/hap-nodejs/lib/Accessory.js:856:22)
```

**Comment by hobbyquaker** [comment]
should be fixed in v0.8.4

**Comment by mattsheffiel** [comment]
Great! I'll try running it again later today.

**Comment by hobbyquaker** [comment]
The UI is now adapted to the multi-service accessory.

**Comment by hobbyquaker** [comment]
A maybe worth mentioning finding I made while playing around: The assignment to a room is always on accessory-level, so it's not possible to have different rooms for services of one accessory.
