### ISSUE TITLE
Light Bulb Color issue

### ISSUE THREAD

**Issue by raufis27** [hobbyquaker/homekit2mqtt#60]
Could you please let me how Light bulb should output color value ? Is it RGB format or ? 
From what I see right now it is just one number. F.e red outputs just 0. Blue 255.

**Comment by raufis27** [comment]
Ok, after some troubleshooting, I see how it works. 
Question can we output all payload numbers as one messages? 
Also why Red color only results 0 ? Example - hey Siri set color to red: 0,100,100. All other colors are fine.

**Comment by hobbyquaker** [comment]
This is the "Hue Saturation Lightness" Color model. See https://en.wikipedia.org/wiki/HSL_and_HSV
Minimum and maximum of the Hue value is red - this is how HSL works. It's an angle around the color-circle. 

About outputting all values at once - I will think about that.

**Comment by hobbyquaker** [comment]
Closing this here, see #67, #78, #65
