### ISSUE TITLE
How to change default login username and password?

### ISSUE THREAD

**Issue by kevinshane** [hobbyquaker/homekit2mqtt#64]
Sir you done a hell of great job ^^.. 
but how to change default login username `homekit` and the password code `031-45-154`?

**Comment by hobbyquaker** [comment]
Thanks for the nice feedback :)

Until now the username is hardcoded and the password is the same as the homekit pin (command line param `--pincode`). See https://github.com/hobbyquaker/homekit2mqtt/blob/master/index.js#L274

If you wish and will put it on the todo to make it configurable ;)

**Comment by hobbyquaker** [comment]
Will close this issue for now, from my point of view it's ok that the web ui authentication uses the homekit pin as password. If you really feel a need for configurable credentials just tell me.
