### ISSUE TITLE
Implement Service AirQualitySensor

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/homekit2mqtt#69]

**Comment by hobbyquaker** [comment]
Nice, thx 👍 will review and merge asap!

**Comment by hobbyquaker** [comment]
43674bebce88199d6fae69339bbd3c8fcf12ab09

**Comment by kevinshane** [comment]
Hi, sorry for the noob question, but how to interactive the pm2.5 sensor with another service say notification in home app? 
For example I would like to receive a notification when the aqi gets high, or start the AirPurifier when aqi gets worse, something like that... I can't seem to find any "interation" inside the ios home app with an apple tv as hub(the automation of this type of sensor is grey out but I do have a PM2.5 and a HCHO sensor already working, and can't find any automation related to "notification")
Would you please guide me through this? Thanks
