### ISSUE TITLE
RGB <-> HSL conversion for lightbulb service

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/homekit2mqtt#78]

**Comment by kevinshane** [comment]
Hi sir, could u please explain what's the correct payloads for the `statusRGB` and `setRGB` topic? Does it reads a hex color code like `#EBD7B8` or just a array of rgb(0-255)value? I try to filled in `EBD7B8FF` for the `statusRGB` topic, it appears obviously not work.

also please consider converting the `hex8` value (eg. EBD7B8FF=RRGGBBWW) inside homekit2mqtt cuz this is what `tasmota` prefer, and somehow many of us are using sonoff devices with tasmota. 

Currently it still needs extra work in node-red to convert the mqtt topic payload to make homekit2mqtt happy.

Thanks sir

**Comment by hobbyquaker** [comment]
Currently it should work with a string containing a 6 digit hex value for RGB (no `#`). This works in my tests. I must admit that I don't know what to do with your 4th tuple ("WW") as RGB already contains the Brightness information (e.g. `FFFFFF` is white at full brightness and `777777` is white at 50% brightness). Will do some more testing as soon as I find time.

**Comment by hobbyquaker** [comment]
Oh yes, thanks for pointing that out. Added the '#'.
