### ISSUE TITLE
mqtt.on "message" always returns "undefined"

### ISSUE THREAD

**Issue by erikgranlund** [hobbyquaker/homekit2mqtt#8]
Hello,

I'm a complete newbie when it comes to JavaScript, so feel free to tell me I'm holding it wrong :)

While trying to get a fake switch to work, I kept encountering an issue where no matter what I published to the MQTT server, homekit2mqtt would always see it as "undefined":
<img width="1152" alt="screen shot 2016-06-02 at 7 20 21 am" src="https://cloud.githubusercontent.com/assets/5056946/15748140/827f8986-2892-11e6-83be-3c4de27962f0.png">

Diving in to the code, noticed 46 of index.js says:

    state = JSON.parse(payload).val;

When I changed that to:

    state = JSON.parse(payload);

It started working.

<img width="1158" alt="screen shot 2016-06-02 at 7 22 59 am" src="https://cloud.githubusercontent.com/assets/5056946/15748239/e8d84b00-2892-11e6-9eab-f8798f5026c0.png">

Is this a bug in the code, or am I doing something wrong?

**Comment by hobbyquaker** [comment]
There is still a bug left. My intention was that JSON-Payloads with val-attribute aren't mandatory, I want it to work with a plain payload also. Thanks for pointing me on this - and big thanks for your efforts in the Wiki!

**Comment by erikgranlund** [comment]
No problem! Thanks for the help!
