### ISSUE TITLE
Battery Voltage to Percentage Conversion

### ISSUE THREAD

**Issue by mattsheffiel** [hobbyquaker/homekit2mqtt#82]
Some of my devices report their battery voltage instead of a percentage. I understand that HomeKit doesn't presently support a voltage characteristic but I was wondering if we could implement a way to handle and convert that within homekit2mqtt. I understand this may be outside of the scope of the software. I'd just like to hear your opinions on the idea.

The way I would see this working is having an option to set the max voltage expected on a device (maybe a config variable?). If that variable is set we could then just do the math ` (currentVoltage / maxVoltage) * 100 ` to calculate a percentage. We could just use the same MQTT topic that the percentage would normally be sent over to keep things simple.

I can accomplish this with other means I'm just trying to minimize the number of scripts and programs I have to run as much as possible.

**Comment by hobbyquaker** [comment]
No problem, we could just introduce a factor like I did e.g. for the LightBulb's Service brightness and hue characteristics (see https://github.com/hobbyquaker/homekit2mqtt/blob/master/services/Lightbulb.js#L52)

**Comment by hobbyquaker** [comment]
hmm after thinking a few minutes - a factor will not be enough because 0% doesn't correpsond to 0V, so an offset would be needed also. Or more comfortable with a min/max setting.

**Comment by mattsheffiel** [comment]
Yes, you are definitely correct. I didn't think about that. Min and max would be necessary.

**Comment by hobbyquaker** [comment]
v0.9.0 introduces payload options `minBatteryLevel` and `maxBatteryLevel`.
