### ISSUE TITLE
Version Changelog ?

### ISSUE THREAD

**Issue by raufis27** [hobbyquaker/homekit2mqtt#84]
Not an issue but suggestion.

**Comment by hobbyquaker** [comment]
Makes sense. :) I will think about how to do it.

**Comment by raufis27** [comment]
Otherwise I have to check every change you make, to see what is new :) 

Thank you so much for your hard work!

**Comment by hobbyquaker** [comment]
So, a first try: https://github.com/hobbyquaker/homekit2mqtt/blob/master/CHANGELOG.md
Not optimal yet, will need much more discipline regarding commit messages and issue creation to get nice and useful changelogs ;-)
