### ISSUE TITLE
Template creation

### ISSUE THREAD

**Issue by NovaGL** [hobbyquaker/homekit2mqtt#87]
I saw you had a templates setup for Hue lights, but it would be good to create custom templates.

That way you can easily prefill the information or even batch import.

Eg my lights work in this format

lights/{room}/{type}/{action}

So it would be 
lights/bed1/lamp/level
lights/bed1/lights/state
lights/bed1/lights/set_brightness
lights/bed1/lights/set_power

If I could easily populate that it would make things easier.

**Comment by hobbyquaker** [comment]
The templates are defined in https://github.com/hobbyquaker/homekit2mqtt/blob/master/ui/templates.js - I think the definition is quite self-explanatory, if you have questions don't hesitate to ask. Pull requests welcome! :-)

**Comment by NovaGL** [comment]
Maybe I should rephrase I want this done via UI


You didn't answer the other part of batch importing devices.
