### ISSUE TITLE
Request - Control homekit devices.

### ISSUE THREAD

**Issue by raufis27** [hobbyquaker/homekit2mqtt#91]
Could you please consider adding feauture to discover and control devices already included in homekit? F.e I have homekit enabled power plug I would like to control it ouside  homekit usin mqtt messages.

https://developer.apple.com/homekit/

Thank you

**Comment by hobbyquaker** [comment]
I consider this as „out of scope“ for homekit2mqtt - but there is mqtt2homekit which does exactly what you‘re asking for:
https://github.com/forty2/mqtt2homekit

**Comment by raufis27** [comment]
Thanks, but mqtt2homekit doesn't work for me. I had hard time installing it and after installation it doesn't run.
