### ISSUE TITLE
noob question: is it possible to add Air-conditioner?

### ISSUE THREAD

**Issue by kevinshane** [hobbyquaker/homekit2mqtt#93]
hey @hobbyquaker Sir, I am facing a problem of how to add AC unit into homekit, I am currently using broadlink rm pro to controlling the ac, it worked like a charm, but have no idea of how to add them into homekit via homekit2mqtt services(and which service?)
Could u please help me through this process? Thanks

**Comment by hobbyquaker** [comment]
I guess that should be possible with the `Thermostat` service

**Comment by kevinshane** [comment]
Hey @hobbyquaker , could you please show us some examples of how to setup? thanks

**Comment by hobbyquaker** [comment]
First you have to make sure that your device can be controlled via MQTT and have knowledge of the required topics and payloads. If you can give me the necessary topics/payloads I can help you with the service config.

**Comment by hobbyquaker** [comment]
Now the HeaterCooler Service is also available, that should be a better fit :)
https://github.com/hobbyquaker/homekit2mqtt/issues/72
