### ISSUE TITLE
Warnings in raspbian

### ISSUE THREAD

**Issue by jsponz** [hobbyquaker/homekit2mqtt#96]
Hi,

Thanks for your nice code. It is amazing. 

I have installed it on Raspberry 3 with Raspbian. 

After launching "homekit2mqtt" I get the following warnings:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
2018-06-17 17:50:36.227 <info>  homekit2mqtt 0.9.6 starting
2018-06-17 17:50:36.238 <info>  mqtt trying to connect...

but it works. 

(links don't work).

Is it anything that I need to worry about?

Thanks,
Jorge

**Comment by hobbyquaker** [comment]
You can safely ignore these warnings. As soon as I update to the latest HAP-Nodejs (will do in the next few weeks) they will be gone.
